apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: remote-mke
  namespace: k0rdent
spec:
  template: mke4k-remote-cluster-standalone-cp-0-0-2
  credential: remote-cred
  config:
    infrastructure:
      controlPlaneNumber: 1
      workersNumber: 1
      apiServerHost: 10.0.0.120
      apiServerPort: 6443
      remoteMachines:
        controlPlane:
        - name: pac-worker-2
          address: 10.0.0.120
          port: 22
          user: ubuntu
          useSudo: true
          sshKeyRef:
            name: remote-ssh-key
        worker:
        - name: pac-worker-3
          address: 10.0.0.21
          port: 22
          user: ubuntu
          useSudo: true
          sshKeyRef:
            name: remote-ssh-key
        - name: pac-worker-4
          address: 10.0.0.10
          port: 22
          user: ubuntu
          useSudo: true
          sshKeyRef:
            name: remote-ssh-key
        - name: pac-worker-5
          address: 10.0.0.81
          port: 22
          user: ubuntu
          useSudo: true
          sshKeyRef:
            name: remote-ssh-key
    k0s:
      version: v1.32.6+k0s.0
      api:
        requestTimeout: 1m0s
      clientRootCASecret: remote-mke-client-root-ca
      controllerManager:
        terminatedPodGCThreshold: 12500
      encryptionConfigSecret: remote-mke-encryption-config 
      extensions:
        charts:
          - chartname: oci://ghcr.io/mirantiscontainers/mirrored-chart-tigera-operator
            name: tigera-operator
            namespace: tigera-operator
            order: 1
            timeout: 10m0s
            values: |-
              kubeletVolumePluginPath: /var/lib/k0s/kubelet
              installation:
                registry: ghcr.io/mirantiscontainers/
                logging:
                  cni:
                    logSeverity: Info
                cni:
                  type: Calico
                kubeletVolumePluginPath: /var/lib/k0s/kubelet
                calicoNetwork:
                  bgp: Disabled
                  linuxDataplane: Iptables
                  ipPools:
                  - cidr: 192.168.0.0/16
                    encapsulation: VXLAN
                    blockSize: 26
              resources:
                requests:
                  cpu: 250m
              tigeraOperator:
                version: v1.36.7
                registry: ghcr.io/mirantiscontainers/
              defaultFelixConfiguration:
                enabled: true
                logSeveritySys: Info
                ipsecLogLevel: Info
                bpfLogLevel: Info
                vxlanPort: 4789
                vxlanVNI: 10000
            version: v3.29.3
      kubelet:
        kubeletRootDir: /var/lib/k0s/kubelet
        managerProfile: mke-default-manager
        workerProfile: mke-default-worker
        workerProfiles:
        - name: mke-default-worker
          values:
            eventRecordQPS: 50
            kubeReserved:
              cpu: 50m
              ephemeral-storage: 500Mi
              memory: 300Mi
            maxPods: 110
            podPidsLimit: -1
            podsPerCore: 0
            protectKernelDefaults: false
            seccompDefault: false
        - name: mke-default-manager
          values:
            eventRecordQPS: 50
            kubeReserved:
              cpu: 250m
              ephemeral-storage: 4Gi
              memory: 2Gi
            maxPods: 110
            podPidsLimit: -1
            podsPerCore: 0
            protectKernelDefaults: false
            seccompDefault: false
      network:
        kubeProxy:
          iptables:
            minSyncPeriod: 0s
            syncPeriod: 0s
          ipvs:
            minSyncPeriod: 0s
            syncPeriod: 0s
            tcpFinTimeout: 0s
            tcpTimeout: 0s
            udpTimeout: 0s
          metricsBindAddress: 0.0.0.0:10249
          mode: iptables
          nftables:
            minSyncPeriod: 0s
            syncPeriod: 0s
        kuberouter:
          autoMTU: true
          hairpin: Enabled
          metricsPort: 8080
        nodePortRange: 33000-35767
        provider: custom
      telemetry:
        enabled: true
    registry:
      chartRegistry:
        url: oci://ghcr.io/mirantiscontainers
      imageRegistry:
        url: ghcr.io/mirantiscontainers
    mke:
      nginxIngress:
        nodePorts:
          https: 33001
          http: 33000
  serviceSpec:
    syncMode: ContinuousWithDriftDetection
    templateResourceRefs:
      - resource:
          apiVersion: v1
          kind: Secret
          name: remote-mke-client-root-ca
        identifier: ClientRootCA
        optional: false
      - resource:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: RemoteCluster
          name: "{{ .Cluster.metadata.name }}"
        identifier: RemoteCluster
        optional: false
    services:
      - name: cert-manager
        namespace: mke
        template: cert-manager-1-18-2
        values: |
          crds:
            enabled: true
            keep: false
          image:
            repository: ghcr.io/mirantiscontainers/jetstack/cert-manager-controller
          webhook:
            image:
              repository: ghcr.io/mirantiscontainers/jetstack/cert-manager-webhook
            tolerations:
              - key: node-role.kubernetes.io/master
                operator: Exists
                effect: NoSchedule
          cainjector:
            image:
              repository: ghcr.io/mirantiscontainers/jetstack/cert-manager-cainjector
            tolerations:
              - key: node-role.kubernetes.io/master
                operator: Exists
                effect: NoSchedule
          startupapicheck:
            image:
              repository: ghcr.io/mirantiscontainers/jetstack/cert-manager-startupapicheck
            tolerations:
              - key: node-role.kubernetes.io/master
                operator: Exists
                effect: NoSchedule
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
      - name: mke-aux-objects
        namespace: mke
        template: mke-aux-objects-0-2-0
        values: |
          clientRootCA:
            certificate: {{ get (getResource "ClientRootCA").data "ca.crt"  }}
            key: {{ get (getResource "ClientRootCA").data "ca.key" }}
          backup:
            enabled: false
            secret:
              name: minio-credentials
              storageProviderType: InCluster
              accessKeyId: admin
              secretAccessKey: "<insert secret key>"
          certificates:
            ingressController:
              enabled: true
            #allowedDomains:
            allowedIPs:
              - '{{ (getResource "RemoteCluster").spec.controlPlaneEndpoint.host }}'
      - name: nginx
        namespace: mke
        template: ingress-nginx-4-12-1
        values: |
          controller:
            admissionWebhooks:
              certManager:
                enabled: true
              patch:
                enabled: false
                image:
                  digest: ""
                  digestChroot: ""
                  registry: ghcr.io/mirantiscontainers
            affinity:
              nodeAffinity: {}
            containerPort:
              http: 80
              https: 443
            extraArgs:
              default-ssl-certificate: mke/mke-ingress.tls
              enable-ssl-passthrough: "false"
              http-port: "80"
              https-port: "443"
            image:
              digest: ""
              digestChroot: ""
              registry: ghcr.io/mirantiscontainers
            ingressClass: nginx-default
            ingressClassResource:
              default: true
              name: nginx-default
            replicaCount: 2
            service:
              enableHTTP: true
              enableHTTPS: true
              externalTrafficPolicy: Cluster
              nodePorts:
                http: 33000
                https: 33001
              ports: {}
              type: NodePort
            tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
              operator: Exists
              value: ""
          global:
            image:
              registry: ghcr.io/mirantiscontainers
      - name: authentication
        namespace: mke
        template: dex-0-23-0
        values: |
          config:
            issuer: https://{{ (getResource "RemoteCluster").spec.controlPlaneEndpoint.host }}:33001/dex
            connectors:
              - config:
                  bindDN: cn=admin,dc=example,dc=org
                  bindPW: <bind password>
                  groupSearch:
                    baseDN: ou=Kube,ou=Perimeters,ou=ApplicationContext,dc=example,dc=org
                    filter: (objectClass=groupofuniquenames)
                    nameAttr: dn
                    userMatchers:
                    - groupAttr: uniqueMember
                      userAttr: dn
                  host: <ldap host>
                  insecureNoSSL: true
                  userSearch:
                    baseDN: dc=example,dc=org
                    emailAttr: mail
                    filter: (objectClass=person)
                    idAttr: uid
                    nameAttr: uid
                    username: uid
                  usernamePrompt: LDAP username
                id: ldap
                name: ldap
                type: ldap
            enablePasswordDB: true
            expiry:
              idTokens: 1h
              refreshTokens:
                absoluteLifetime: 24h
            storage:
              type: kubernetes
              config:
                inCluster: true
            web:
              http: 127.0.0.1:5556
              https: 127.0.0.1:5554
              tlsCert: /etc/dex/certs/tls/tls.crt
              tlsKey: /etc/dex/certs/tls/tls.key
              tlsMinVersion: 1.2
              tlsMaxVersion: 1.3
            grpc:
              addr: 127.0.0.1:5557
              tlsCert: /etc/dex/certs/grpc/tls.crt
              tlsKey: /etc/dex/certs/grpc/tls.key
              tlsClientCA: /etc/dex/certs/grpc/ca.crt
            frontend:
              issuer: Mirantis Kubernetes Engine
              dir: /srv/dex/web
              theme: light
            oauth2:
              skipApprovalScreen: true
            staticClients:
            - id: mke-dashboard
              redirectURIs:
              - https://127.0.0.1:3000
              - https://localhost:3000
              - https://{{ .Cluster.spec.controlPlaneEndpoint.host }}:33001
              name: MKE Dashboard
              secret: WFpBHxlwUkbexwTZzIpDra24v
            - id: kubelogin
              name: Kubernetes
              public: true
              redirectURIs:
              - http://localhost:8000
              - http://localhost:18000
              - /device/callback
          volumeMounts:
          - name: https
            mountPath: /etc/dex/certs/tls/
            readOnly: true
          - name: dex-web
            mountPath: /srv/dex/web
            readOnly: true
          - name: grpc
            mountPath: /etc/dex/certs/grpc/
            readOnly: true
          volumes:
          - name: https
            secret:
              secretName: auth-https.tls
          - name: dex-web
            configMap:
              name: dex-web
              items:
              - key: approval.html
                path: templates/approval.html
              - key: atlassian-crowd-icon.svg
                path: static/img/atlassian-crowd-icon.svg
              - key: bitbucket-icon.svg
                path: static/img/bitbucket-icon.svg
              - key: device.html
                path: templates/device.html
              - key: device_success.html
                path: templates/device_success.html
              - key: email-icon.svg
                path: static/img/email-icon.svg
              - key: error.html
                path: templates/error.html
              - key: footer.html
                path: templates/footer.html
              - key: gitea-icon.svg
                path: static/img/gitea-icon.svg
              - key: github-icon.svg
                path: static/img/github-icon.svg
              - key: gitlab-icon.svg
                path: static/img/gitlab-icon.svg
              - key: google-icon.svg
                path: static/img/google-icon.svg
              - key: header.html
                path: templates/header.html
              - key: keystone-icon.svg
                path: static/img/keystone-icon.svg
              - key: ldap-icon.svg
                path: static/img/ldap-icon.svg
              - key: linkedin-icon.svg
                path: static/img/linkedin-icon.svg
              - key: login.html
                path: templates/login.html
              - key: logo.svg
                path: themes/light/logo.svg
              - key: main.css
                path: static/main.css
              - key: microsoft-icon.svg
                path: static/img/microsoft-icon.svg
              - key: oidc-icon.svg
                path: static/img/oidc-icon.svg
              - key: oob.html
                path: templates/oob.html
              - key: password.html
                path: templates/password.html
              - key: robots.txt
                path: robots.txt
              - key: saml-icon.svg
                path: static/img/saml-icon.svg
              - key: styles.css
                path: themes/light/styles.css
          - name: grpc
            secret:
              secretName: auth-grpc.tls
          https:
            enabled: true
          grpc:
            enabled: true
          service:
            type: ClusterIP
          tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            value: ""
            effect: NoSchedule
            tolerationseconds: null
          ingress:
            enabled: true
            className: nginx-default
            hosts:
            - host: ""
              paths:
              - path: /dex
                pathType: Prefix
          image:
            repository: ghcr.io/mirantiscontainers/dexidp/dex
      - name: dex-http-server
        namespace: mke
        template: dex-http-server-chart-0-3-0 
        values: |
          image:
            repository: ghcr.io/mirantiscontainers/dex-http-server
            tag: v0.7.0
          tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            value: ""
            effect: NoSchedule
            tolerationseconds: null
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          ingress:
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /$2
            className: nginx-default
            hosts:
            - host: ""
              paths:
              - path: /api/dex(/|$)(.*)
                pathType: ImplementationSpecific
      - name: monitoring
        namespace: mke
        template: kube-prometheus-stack-57-2-0
        values: |
          global:
              imageRegistry: ghcr.io/mirantiscontainers
          grafana:
              enabled: true
              tolerations:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                    value: ""
                    effect: NoSchedule
                    tolerationseconds: null
          alertmanager:
              enabled: false
              alertmanagerSpec:
                  tolerations:
                      - key: node-role.kubernetes.io/master
                        operator: Exists
                        value: ""
                        effect: NoSchedule
                        tolerationseconds: null
          kubeEtcd:
              service: {}
              serviceMonitor: {}
          prometheus:
              prometheusSpec:
                  serviceMonitorSelectorNilUsesHelmValues: false
                  serviceMonitorNamespaceSelector:
                      matchExpressions:
                          - key: kubernetes.io/metadata.name
                            operator: Exists
                  tolerations:
                      - key: node-role.kubernetes.io/master
                        operator: Exists
                        value: ""
                        effect: NoSchedule
          kubelet:
              serviceMonitor:
                  cAdvisor: true
          kube-state-metrics:
              tolerations:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                    value: ""
                    effect: NoSchedule
                    tolerationseconds: null
          prometheusOperator:
              tolerations:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                    value: ""
                    effect: NoSchedule
                    tolerationseconds: null
              admissionWebhooks:
                  patch:
                      tolerations:
                          - key: node-role.kubernetes.io/master
                            operator: Exists
                            value: ""
                            effect: NoSchedule
                            tolerationseconds: null
      - name: ui
        namespace: mke
        template: mke-dashboard-chart-1-7-0
        values: |
          image:
              repository: ghcr.io/mirantiscontainers/mke-dashboard
              tag: v1.6.2
          tolerations:
              - key: node-role.kubernetes.io/master
                operator: Exists
                value: ""
                effect: NoSchedule
                tolerationseconds: null
          nodeSelector:
              node-role.kubernetes.io/control-plane: "true"
          ingress:
              enabled: true
              className: nginx-default
              hosts:
                  - host: ""
                    paths:
                      - path: /
                        pathType: Prefix
      - name: node-feature-discovery
        namespace: mke
        template: node-feature-discovery-0-17-2
        values: |
          image:
              repository: ghcr.io/mirantiscontainers/nfd/node-feature-discovery
          master:
              nodeSelector:
                  kubernetes.io/os: linux
          worker:
              nodeSelector:
                  kubernetes.io/os: linux
              tolerations:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                    effect: NoSchedule
          gc:
              tolerations:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                    effect: NoSchedule
