apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "cluster.name" . }}
  {{- if .Values.infrastructure.clusterLabels }}
  labels: {{- toYaml .Values.infrastructure.clusterLabels | nindent 4}}
  {{- end }}
  {{- if .Values.infrastructure.clusterAnnotations }}
  annotations: {{- toYaml .Values.infrastructure.clusterAnnotations | nindent 4}}
  {{- end }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - {{ .Values.clusterNetwork.podsCIDR }}
    services:
      cidrBlocks:
        - {{ .Values.clusterNetwork.servicesCIDR }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0sControlPlane
    name: {{ include "k0scontrolplane.name" .  }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteCluster
    name: {{ include "cluster.name" . }}