{{- $global := .Values.global | default dict }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: {{ include "k0sworkerconfigtemplate.name" . }}
spec:
  template:
    spec:
      files:
        {{- if or .Values.registry.imageRegistry.caData .Values.registry.chartRegistry.caData }}
        - content: |
            version = 2
            
            [plugins."io.containerd.grpc.v1.cri".registry]
              config_path = "/etc/containerd/certs.d"
          path: "/etc/k0s/containerd.d/registry-config.toml"
          permissions: "0644"
          {{- range $_, $registryData := .Values.registry }}
            {{- if $registryData.caData }}
        - content: |
            {{ $registryData.caData | nindent 8 }}
          permissions: "0664"
          path: /etc/containerd/certs.d/{{ (urlParse $registryData.url).host }}/ca.crt
            {{- end }}
          {{- end }}
        {{- end }}
      useSystemHostname: true
      args:
      - --debug=true
      - --kubelet-extra-args={{ include "kubeletArgs" .Values.k0s.kubelet.extraArgs }}
      - --kubelet-root-dir={{ default "/var/lib/kubelet" .Values.k0s.kubelet.kubeletRootDir }}
      - --profile={{ default "mke-default-worker" .Values.k0s.kubelet.workerProfile }}
      version: {{ .Values.k0s.version }}
