apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteCluster
metadata:
  name: {{ include "cluster.name" . }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.clusterNetwork.apiServerHost }}
    port: {{ .Values.clusterNetwork.apiServerPort }}
