---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachineTemplate
metadata:
  name: {{ include "remotemachinetemplate.controlplane.name" . }}
spec:
  template:
    spec:
      pool: cp

---
{{- range $index, $machine := .Values.remoteMachines.controlPlane }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PooledRemoteMachine
metadata:
  name: {{ $machine.name }}
spec:
  pool: cp
  machine:
    address: {{ $machine.address }}
    port: {{ $machine.port | default 22 }}
    user: {{ $machine.user | default "root" }}
    useSudo: {{ $machine.useSudo | default true }}
    sshKeyRef:
      name: {{ $machine.sshKeyRef.name }}
---
{{- end }}
