apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: $KCM_NAMESPACE
  labels:
    k0rdent.mirantis.com/managed: "true"
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
spec:
  url: https://charts.jetstack.io
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: cert-manager-1-18-2
  namespace: $KCM_NAMESPACE
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cert-manager
      version: 1.18.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: jetstack
---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: mke-aux-objects-0-2-0
  namespace: $KCM_NAMESPACE
spec:
  helm:
    chartSpec:
      chart: mke-aux-objects
      interval: 10m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mke-charts
      version: 0.2.0
